openapi: 3.0.0
info:
  version: 0.0.1
  title: catfood-course-homework
  description: 理论课程教学作业模块 API
servers:
  - url: "http://localhost:8000/api/v1/course-homework"

paths:
  /{courseId}/homework/:
    get:
      summary: "按照页码和每页数目获取某门课程下的作业列表"
      operationId: get-homework-list-within-course
      tags:
        - course-homework
      parameters:
        - name: itemCountOnOnePage
          in: query
          description: 一页返回的个数
          required: false
          schema:
            type: integer
            format: int32
        - name: pageIndex
          in: query
          description: 页码
          required: false
          schema:
            type: integer
            format: int32
      responses:
        "200":
          description: "OK"
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: "#/components/schemas/courseHomework"
        "400":
          description: "Bad Request"
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/badRequest"
        "403":
          description: "Permission Denied - provided user has no permission to access the course"
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/permissionDenied"
        "404":
          description: "Not Found - course not found"
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/notFound"
        default:
          description: Unexpected error
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Error"
    post:
      summary: "创建一次新作业"
      operationId: create-homework
      tags:
        - course-homework
      parameters:
        - name: homeworkTitle
          in: query
          description: 作业标题
          required: true
          schema:
            type: string
        - name: homeworkDescription
          in: query
          description: 作业描述
          required: true
          schema:
            type: string
      requestBody:
        required: true
        content:
          multipart/form-data:
            schema:
              type: string
              format: binary
      responses:
        "201":
          description: "Created - Successfully created new homework"
          content:
            application/json:
              schema:
                type: object
                items:
                  $ref: "#/components/schemas/courseHomework"
        "400":
          description: "Bad Request"
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/badRequest"
        "403":
          description: "Permission Denied - provided user has no permission to manage the course"
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/permissionDenied"
        "404":
          description: "Not Found - course or homework not found"
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/notFound"
        default:
          description: Unexpected error
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Error"
  /{courseId}/homework/{homeworkId}:
    get:
      summary: "获取某门课程下的某次作业详细信息（非提交文件）"
      operationId: get-homework-detail
      tags:
        - course-homework
      responses:
        "200":
          description: "OK - Successfully obtained course homework details"
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: "#/components/schemas/courseHomework"
        "400":
          description: "Bad Request"
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/badRequest"
        "403":
          description: "Permission Denied - provided user has no permission to access the course, or given homework is not within the course."
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/permissionDenied"
        "404":
          description: "Not Found - course or homework not found"
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/notFound"
        default:
          description: Unexpected error
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Error"
    put:
      summary: "更改作业信息"
      operationId: get-homework-detail
      tags:
        - course-homework
      parameters:
        - name: homeworkTitle
          in: query
          description: 作业标题
          required: true
          schema:
            type: string
        - name: homeworkDescription
          in: query
          description: 作业描述
          required: true
          schema:
            type: string
      requestBody:
        required: true
        content:
          multipart/form-data:
            schema:
              type: string
              format: binary
      responses:
        "200":
          description: "OK - Course homework details is successfullt altered"
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: "#/components/schemas/courseHomework"
        "400":
          description: "Bad Request"
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/badRequest"
        "403":
          description: "Permission Denied - provided user has no permission to manage the course"
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/permissionDenied"
        "404":
          description: "Not Found - course or homework not found"
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/notFound"
        default:
          description: Unexpected error
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Error"
    
  /{courseId}/homework/{homeworkId}/file:
    get:
      summary: "按照页码和每页数目获取某门课的课件列表"
      operationId: get-file-list-for-homework
      tags:
        - course-homework
      parameters:
        - name: itemCountOnOnePage
          in: query
          description: 一页返回的个数
          required: false
          schema:
            type: integer
            format: int32
        - name: pageIndex
          in: query
          description: 页码
          required: false
          schema:
            type: integer
            format: int32
      responses:
        "200":
          description: "OK - Successfully obtained course homework file list"
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: "#/components/schemas/courseHomeworkFile"
        "400":
          description: "Bad Request"
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/badRequest"
        "403":
          description: "Permission Denied - provided user has no permission to access the course, or given homework is not within the course."
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/permissionDenied"
        "404":
          description: "Not Found - course not found"
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/notFound"
        default:
          description: Unexpected error
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Error"
    post:
      summary: "学生提交作业（覆盖原有作业）"
      operationId: handin-homework
      tags:
        - course
      requestBody:
        required: true
        content:
          multipart/form-data:
            schema:
              type: string
              format: binary
      responses:
        "200":
          description: "OK - Successfully rewrite original file"
          content:
            application/json:
              schema:
                type: object
                items:
                  $ref: "#/components/schemas/courseHomeworkFile"
        "201":
          description: "Created - Successfully created new file"
          content:
            application/json:
              schema:
                type: object
                items:
                  $ref: "#/components/schemas/courseHomeworkFile"
        "400":
          description: "Bad Request"
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/badRequest"
        "403":
          description: "Permission Denied - provided user has no permission to access the course, or given homework is not within the course."
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/permissionDenied"
        "404":
          description: "Not Found - course not found"
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/notFound"
        "409":
          description: "Conflict - two same file in one course"
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/conflict"
        default:
          description: Unexpected error
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Error"
  /course/{courseId}/count:
    get:
      summary: "获取某门课共有多少课件"
      operationId: get-file-list-for-course
      tags:
        - course
      responses:
        "200":
          description: "OK - Successfully obtained the count of files from currrent course"
          content:
            application/json:
              schema:
                type: object
                items:
                  $ref: "#/components/schemas/courseFileCount"
        "400":
          description: "Bad Request"
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/badRequest"
        "403":
          description: "Permission Denied - provided user has no permission to access the course, or given homework is not within the course."
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/permissionDenied"
        "404":
          description: "Not Found - course or file not found"
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/notFound"
        default:
          description: Unexpected error
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Error"
  /course/{courseId}/{fileId}:
    get:
      summary: "获取文件"
      operationId: get-file-for-course
      tags:
        - course
      responses:
        "200":
          description: "OK - Successfully obtained course file"
          content:
            application/octet-stream:
              schema:
                type: string
                format: binary
        "400":
          description: "Bad Request"
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/badRequest"
        "403":
          description: "Permission Denied - provided user has no permission to access the course, or given homework is not within the course."
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/permissionDenied"
        "404":
          description: "Not Found - course or file not found"
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/notFound"
        default:
          description: Unexpected error
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Error"
    put:
      summary: "修改文件注释"
      operationId: change-file-comments
      tags:
        - course
      parameters:
        - name: fileComment
          in: query
          description: 文件注释
          required: true
          schema:
            type: string
      responses:
        "200":
          description: "OK - Successfully changed course file description"
          content:
            application/json:
              schema:
                type: object
                items:
                  $ref: "#/components/schemas/courseFile"
        "400":
          description: "Bad Request"
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/badRequest"
        "403":
          description: "Permission Denied - provided user has no permission to access the course, or given homework is not within the course."
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/permissionDenied"
        "404":
          description: "Not Found - course or file not found"
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/notFound"
        default:
          description: Unexpected error
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Error"
    delete:
      summary: "删除该文件资源"
      operationId: delete-file
      tags:
        - course
      responses:
        "200":
          description: "OK - File is successfully deleted"
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/ok"
        "400":
          description: "Bad Request"
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/badRequest"
        "403":
          description: "Permission Denied - provided user has no permission to access the course, or given homework is not within the course."
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/permissionDenied"
        "404":
          description: "Not Found - course or file not found"
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/notFound"
        default:
          description: Unexpected error
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Error"

components:
  schemas:
    courseFile:
      type: object
      required:
        - fileUuid
        - fileDisplayName
        - fileComments
        - fileCreateTime
        - fileUpdateTime
        - fileCreatorId
        - fileSize
      properties:
        fileUuid:
          type: string
        fileDisplayName:
          type: string
        fileComments:
          type: string
        fileCreateTime:
          type: string
          format: date-time
        fileUpdateTime:
          type: string
          format: date-time
        fileCreatorId:
          type: string
        fileSize:
          type: integer
          format: int32
    courseFileCount:
      type: object
      required:
        - courseId
        - courseFileCount
      properties:
        courseId:
          type: string
        courseFileCount:
          type: integer
          format: int32
    ok:
      title: OK
      type: object
      properties:
        error:
          type: object
          properties:
            message:
              type: string
    badRequest:
      title: Bad Request
      type: object
      properties:
        error:
          type: object
          properties:
            message:
              type: string
    permissionDenied:
      title: Permission Denied
      type: object
      properties:
        error:
          type: object
          properties:
            message:
              type: string
    notFound:
      title: Not Found
      type: object
      properties:
        error:
          type: object
          properties:
            message:
              type: string
    conflict:
      title: Conflict
      type: object
      properties:
        error:
          type: object
          properties:
            message:
              type: string
    Error:
      type: object
      required:
        - message
      properties:
        error:
          type: object
          properties:
            message:
              type: string
