openapi: 3.0.0
info:
  version: 0.0.1
  title: catfood-contest
  description: 对抗模块 API
servers:
  - url: 'http://localhost:8000/api/v1/contest'
paths:
  /matches:
    get:
      summary: '获取某个学生在某门课程的参加比赛历史'
      operationId: get-mateches
      tags:
        - match
      parameters:
        - name: studentId
          in: query
          description: 查询的学生id
          required: true
          schema:
            type: integer
            format: int32
        - name: courseId
          in: query
          description: 查询的课程id
          required: true
          schema:
            type: integer
            format: int32
      responses:
        '200':
          description: 'OK - Successfully obtained match list'
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/matches'
        '400':
          description: 'Bad Request - Invalid user ID or course ID supplied'
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/badRequest'
        '404':
          description: 'Not Found - contest not found'
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/notFound'
        default:
          description: Unexpected error
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'
components:
  schemas:
    matches:
      type: object
      required:
        - matchId
        - constestId
        - timeStamp
        - title
        - participantNumber
        - startTime
        - endTime
        - chapter
        - description
        - rank
        - score
      properties:
        matchId:
          type: integer
          format: int64
        constestId:
          type: integer
          format: int64
        timeStamp:
          type: string
          format: date-time
        title:
          type: string
        participantNumber:
          type: integer
          format: int64
        startTime:
          type: string
          format: date-time
        endTime:
          type: string
          format: date-time
        chapter:
          type: integer
          format: int64
        description:
          type: string
        rank:
          type: integer
          format: int64
        score:
          type: integer
          format: int64
    badRequest:
      title: Bad Request
      type: object
      properties:
        error:
          type: object
          properties:
            message:
              type: string
    notFound:
      title: Not Found
      type: object
      properties:
        error:
          type: object
          properties:
            message:
              type: string
    Error:
      type: object
      required:
        - message
      properties:
        error:
          type: object
          properties:
            message:
              type: string
