openapi: 3.0.0
info:
  version: 0.0.1
  title: catfood-course-databse
  description: 课程资料库模块 API
servers:
  - url: "http://localhost:8000/api/v1/course-database/course-file-database"

paths:
  /course/{courseId}:
    get:
      summary: "按照页码和每页数目获取某门课的课件列表"
      operationId: get-file-list-for-course
      tags:
        - course
      parameters:
        - name: courseId
          in: path
          description: 课程 ID
          required: true
          schema:
            type: string
        - name: itemCountOnOnePage
          in: query
          description: 一页返回的个数
          required: false
          schema:
            type: integer
            format: int32
        - name: pageIndex
          in: query
          description: 页码
          required: false
          schema:
            type: integer
            format: int32
      responses:
        "200":
          description: "OK - Successfully obtained course file list"
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: "#/components/schemas/courseFile"
        "400":
          description: "Bad Request"
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/badRequest"
        "403":
          description: "Permission Denied - provided user has no permission to access the course"
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/permissionDenied"
        "404":
          description: "Not Found - course not found"
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/notFound"
        default:
          description: Unexpected error
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Error"
    post:
      summary: "增加新的文件"
      operationId: add-new-file-for-course
      tags:
        - course
      parameters:
        - name: courseId
          in: path
          description: 课程 ID
          required: true
          schema:
            type: string
      responses:
        "201":
          description: "Created - Successfully created new file"
          headers:
            FILE_PUT_URL:
              description: generated POST URL of the file
              schema:
                type: string
          content:
            application/json:
              schema:
                type: object
                $ref: "#/components/schemas/courseFile"
        "400":
          description: "Bad Request"
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/badRequest"
        "403":
          description: "Permission Denied - provided user has no permission to write to the course"
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/permissionDenied"
        "404":
          description: "Not Found - course not found"
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/notFound"
        "409":
          description: "Conflict - two same file in one course"
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/conflict"
        default:
          description: Unexpected error
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Error"
  /course/{courseId}/count:
    get:
      summary: "获取某门课共有多少课件"
      operationId: get-file-list-for-course
      tags:
        - course
      parameters:
        - name: courseId
          in: path
          description: 课程 ID
          required: true
          schema:
            type: string
      responses:
        "200":
          description: "OK - Successfully obtained the count of files from currrent course"
          content:
            application/json:
              schema:
                type: object
                $ref: "#/components/schemas/courseFileCount"
        "400":
          description: "Bad Request"
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/badRequest"
        "403":
          description: "Permission Denied - provided user has no permission to access the course"
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/permissionDenied"
        "404":
          description: "Not Found - course or file not found"
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/notFound"
        default:
          description: Unexpected error
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Error"
  /course/{courseId}/{fileId}:
    get:
      summary: "获取文件元数据"
      operationId: get-file-metadata-for-course
      tags:
        - course
      parameters:
        - name: courseId
          in: path
          description: 课程 ID
          required: true
          schema:
            type: string
        - name: fileId
          in: path
          description: 文件 ID
          required: true
          schema:
            type: string
      responses:
        "200":
          description: "OK - Successfully obtained file metadata"
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/courseFile"
        "400":
          description: "Bad Request"
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/badRequest"
        "403":
          description: "Permission Denied - provided user has no permission to access the course"
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/permissionDenied"
        "404":
          description: "Not Found - course or file not found"
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/notFound"
        default:
          description: Unexpected error
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Error"
    put:
      summary: "修改文件注释"
      operationId: change-file-comments
      tags:
        - course
      parameters:
        - name: courseId
          in: path
          description: 课程 ID
          required: true
          schema:
            type: string
        - name: fileId
          in: path
          description: 文件 ID
          required: true
          schema:
            type: string
        - name: fileComment
          in: query
          description: 文件注释
          required: true
          schema:
            type: string
      responses:
        "200":
          description: "OK - Successfully changed course file description"
          content:
            application/json:
              schema:
                type: object
                $ref: "#/components/schemas/courseFile"
        "400":
          description: "Bad Request"
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/badRequest"
        "403":
          description: "Permission Denied - provided user has no permission to write to the course"
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/permissionDenied"
        "404":
          description: "Not Found - course or file not found"
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/notFound"
        default:
          description: Unexpected error
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Error"
    delete:
      summary: "删除该文件资源"
      operationId: delete-file
      tags:
        - course
      parameters:
        - name: courseId
          in: path
          description: 课程 ID
          required: true
          schema:
            type: string
        - name: fileId
          in: path
          description: 文件 ID
          required: true
          schema:
            type: string
      responses:
        "200":
          description: "OK - File is successfully deleted"
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/ok"
        "400":
          description: "Bad Request"
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/badRequest"
        "403":
          description: "Permission Denied - provided user has no permission to write to the course"
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/permissionDenied"
        "404":
          description: "Not Found - course or file not found"
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/notFound"
        default:
          description: Unexpected error
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Error"
  /course/{courseId}/{fileId}/file:
    get:
      summary: "获取文件"
      operationId: get-file-for-course
      tags:
        - course
      parameters:
        - name: courseId
          in: path
          description: 课程 ID
          required: true
          schema:
            type: string
        - name: fileId
          in: path
          description: 文件 ID
          required: true
          schema:
            type: string
      responses:
        "302":
          description: "Found - Redirecting according to the url generated"
          headers:
            location:
              description: generated URL of the file
              schema:
                type: string

        "400":
          description: "Bad Request"
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/badRequest"
        "403":
          description: "Permission Denied - provided user has no permission to access the course"
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/permissionDenied"
        "404":
          description: "Not Found - course or file not found"
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/notFound"
        default:
          description: Unexpected error
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Error"

components:
  schemas:
    courseFile:
      type: object
      required:
        - fileUuid
        - fileDisplayName
        - fileComments
        - fileCreateTime
        - fileUpdateTime
        - fileCreatorId
        - fileSize
        - fileToken
      properties:
        fileUuid:
          type: string
        fileDisplayName:
          type: string
        fileComments:
          type: string
        fileCreateTime:
          type: string
          format: date-time
        fileUpdateTime:
          type: string
          format: date-time
        fileCreatorId:
          type: string
        fileSize:
          type: integer
          format: int32
        fileToken:
          type: string
    courseFileLink:
      type: object
      required:
        - fileLink
      properties:
        fileLink:
          type: string
    courseFileCount:
      type: object
      required:
        - courseId
        - courseFileCount
      properties:
        courseId:
          type: string
        courseFileCount:
          type: integer
          format: int32
    ok:
      title: OK
      type: object
      properties:
        error:
          type: object
          properties:
            message:
              type: string
    badRequest:
      title: Bad Request
      type: object
      properties:
        error:
          type: object
          properties:
            message:
              type: string
    permissionDenied:
      title: Permission Denied
      type: object
      properties:
        error:
          type: object
          properties:
            message:
              type: string
    notFound:
      title: Not Found
      type: object
      properties:
        error:
          type: object
          properties:
            message:
              type: string
    conflict:
      title: Conflict
      type: object
      properties:
        error:
          type: object
          properties:
            message:
              type: string
    Error:
      type: object
      required:
        - message
      properties:
        error:
          type: object
          properties:
            message:
              type: string
